### PR TITLE
3.0 release branch

### PR DESCRIPTION
**Pull request by vitorbrandao**

### CODE REVIEW

**Comment by NielsJanssen** [comment]
Hi, is this pull ready to be merged? I think it is, I've been using it in production for well over half a year now and I haven't encountered any issues so far :)

Only thing that seems to be holding back the tests is the PHP 5.6 support, which is EOL by now so it might be worth dropping support.

**Comment by noisebleed** [comment]
Hi @NielsJanssen. Thanks for the feedback! I'm going to drop 5.6 support and give it another try.

**Comment by vitorbrandao** [comment]
Changes included in this pull request have now been incorporated in the `master` branch via another PR. I've used a different branch so I could rebase and apply changes cleanly without affecting this PR and its branch alias which is being picked by Packagist (`3.0.x-dev`).

**Comment by vitorbrandao** [comment]
> Changes included in this pull request have now been incorporated in the `master` branch via another PR. I've used a different branch so I could rebase and apply changes cleanly without affecting this PR and its branch alias which is being picked by Packagist (`3.0.x-dev`).

cc @NielsJanssen

**Pull request closed without merging**
