### PR TITLE
Release 2.0: Support Symfony 3.0

### LINKED ISSUE #48: Symfony3
Hey!

This package isn't allow installing for Symfony 3. But I think it should works.
Can you make it installable via composer for symfony3 ?  :-)

Thanks!

### PR DESCRIPTION
**Pull request by davidfuhr**
This pull request aims to support Symfony 2.8 and Symfony 3.0+. This closes #48.

This is still work in progress.

If you want to support me please create pull requests against the 2.0-branch in my fork: https://github.com/davidfuhr/SmartyBundle/tree/2.0

### CODE REVIEW

**Comment by noisebleed** [comment]
Hi @davidfuhr, is this branch still work in progress?

**Comment by davidfuhr** [comment]
I didn't have time to work on this recently. If I remember correctly most of the stuff worked but I'm not really sure what was missing. I hope to find some soon to document the current state of development.

**Comment by davidfuhr** [comment]
I've cleared all deprecation messages in Symfony 3 and tested it with my existing application. Will you merge it to master and release as v2.0.0?

**Comment by noisebleed** [comment]
This is an impressive merge request! I can't thank you enough for all the hard work on this. Give me some time go through the changes. This will definitely make it to master. Thanks again @davidfuhr!

**Pull request merged**
